<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[emailiddemo@gmail.com]]>
    </line>
    <line>
      <![CDATA[passwordpassword]]>
    </line>
    <line>
      <![CDATA[emailidpraveenkumar@gmail.com]]>
    </line>
    <line>
      <![CDATA[passwordpraveenkumar]]>
    </line>
    <line>
      <![CDATA[emailidpraveen@gmail.com]]>
    </line>
    <line>
      <![CDATA[passwordmypass]]>
    </line>
  </reporter-output>
  <suite name="Default Suite" duration-ms="17919" started-at="2023-04-11T15:28:08Z" finished-at="2023-04-11T15:28:26Z">
    <groups>
    </groups>
    <test name="java" duration-ms="17919" started-at="2023-04-11T15:28:08Z" finished-at="2023-04-11T15:28:26Z">
      <class name="org.example.OnlineClass.datadrivenframe">
        <test-method status="PASS" signature="open()[pri:0, instance:org.example.OnlineClass.datadrivenframe@67b64c45]" name="open" is-config="true" duration-ms="5170" started-at="2023-04-11T15:28:08Z" finished-at="2023-04-11T15:28:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="FAIL" signature="test(java.lang.String, java.lang.String)[pri:0, instance:org.example.OnlineClass.datadrivenframe@67b64c45]" name="test" duration-ms="4057" started-at="2023-04-11T15:28:14Z" data-provider="login" finished-at="2023-04-11T15:28:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[demo@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nopCommerce demo store. Login] but found [nopCommerce demo store. Shopping Cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store. Login] but found [nopCommerce demo store. Shopping Cart]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.example.OnlineClass.datadrivenframe.test(datadrivenframe.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[emailiddemo@gmail.com]]>
            </line>
            <line>
              <![CDATA[passwordpassword]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="test(java.lang.String, java.lang.String)[pri:0, instance:org.example.OnlineClass.datadrivenframe@67b64c45]" name="test" duration-ms="4450" started-at="2023-04-11T15:28:18Z" data-provider="login" finished-at="2023-04-11T15:28:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[praveenkumar@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[praveenkumar]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[emailidpraveenkumar@gmail.com]]>
            </line>
            <line>
              <![CDATA[passwordpraveenkumar]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(java.lang.String, java.lang.String)[pri:0, instance:org.example.OnlineClass.datadrivenframe@67b64c45]" name="test" duration-ms="1949" started-at="2023-04-11T15:28:23Z" data-provider="login" finished-at="2023-04-11T15:28:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[praveen@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mypass]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nopCommerce demo store. Login] but found [nopCommerce demo store. Shopping Cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store. Login] but found [nopCommerce demo store. Shopping Cart]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.example.OnlineClass.datadrivenframe.test(datadrivenframe.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[emailidpraveen@gmail.com]]>
            </line>
            <line>
              <![CDATA[passwordmypass]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="close()[pri:0, instance:org.example.OnlineClass.datadrivenframe@67b64c45]" name="close" is-config="true" duration-ms="808" started-at="2023-04-11T15:28:25Z" finished-at="2023-04-11T15:28:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- org.example.OnlineClass.datadrivenframe -->
    </test> <!-- java -->
  </suite> <!-- Default Suite -->
</testng-results>
